name: Build JOSE Draft 📃
on: push
jobs:
  paper:
    name: Build Paper Draft 🔧
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 🛎️
      uses: actions/checkout@v2
    - name: Build draft PDF 📝
      uses: openjournals/openjournals-draft-action@master
      with:
        journal: jose
        paper-path: paper/paper.md
    - name: Upload draft PDF 📤
      uses: actions/upload-artifact@v1
      with:
        name: jose-draft
        path: paper/paper.pdf
